Repository ABenchM/abm-frontend, pull requests merged in 2019-03, with the labels that each got.

#308 Feat/fix281
  package.json
  src/app/search/search.component.css
  src/app/search/search.component.html
Labels: UI formatting issue

#310 existing email can not be reused for creating a new account
  src/app/register/register.component.html
  src/app/register/register.component.ts
  src/app/services/register.service.ts
Labels: enhancement

#315 updated edit collection page with use of angular material
  src/app/edit-collection/edit-collection.component.css
  src/app/edit-collection/edit-collection.component.html
  src/app/edit-collection/edit-collection.component.spec.ts
  src/app/edit-collection/edit-collection.component.ts
Labels: enhancement

#326 Feat/fix 320
  src/app/forget-password/forget-password.component.css
  src/app/forget-password/forget-password.component.html
  src/app/register/register.component.spec.ts
  src/app/reset-password/reset-password.component.css
  src/app/reset-password/reset-password.component.html
Labels: UI formatting issue, enhancement

#294 Project api integration
  src/app/add-to-collection/add-to-collection.component.html
  src/app/add-to-collection/add-to-collection.component.ts
  src/app/app.module.ts
  src/app/collection/collection.component.html
  src/app/collection/collection.component.ts
  src/app/create-collection/create-collection.component.ts
  src/app/edit-collection/edit-collection.component.css
  src/app/edit-collection/edit-collection.component.html
  src/app/edit-collection/edit-collection.component.ts
  src/app/home/home.component.css
  src/app/home/home.component.html
  src/app/home/home.component.ts
  src/app/parentview/parentview.component.css
  src/app/parentview/parentview.component.html
  src/app/parentview/parentview.component.spec.ts
  src/app/parentview/parentview.component.ts
  src/app/search/search.component.html
  src/app/search/search.component.spec.ts
  src/app/search/search.component.ts
  src/app/services/collection.service.ts
  src/app/services/commit.service.ts
  src/app/view/view.component.css
  src/app/view/view.component.html
  src/app/view/view.component.ts
Labels: high priority
